"""CL7: add pelotao

Revision ID: 2145d4dc8c0b
Revises: 6f613f2da1c7
Create Date: 2025-09-29 11:06:59.793924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2145d4dc8c0b'
down_revision = '6f613f2da1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl7', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pelotao', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_cl7_pelotao'), ['pelotao'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl7', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cl7_pelotao'))
        batch_op.drop_column('pelotao')

    # ### end Alembic commands ###
