"""classe 2 update

Revision ID: 4b298bbd2465
Revises: ecef16cd70e3
Create Date: 2025-12-01 14:38:50.880114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b298bbd2465'
down_revision = 'ecef16cd70e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('necessidade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qtd_cautelada', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl2', schema=None) as batch_op:
        batch_op.drop_column('observacoes')
        batch_op.drop_column('qtd_cautelada')
        batch_op.drop_column('necessidade')

    # ### end Alembic commands ###
