"""add CL7

Revision ID: 4dc051799b11
Revises: 76899bc775ac
Create Date: 2025-09-23 13:07:49.526795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc051799b11'
down_revision = '76899bc775ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cl7',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material', sa.String(length=120), nullable=False),
    sa.Column('situacao', sa.String(length=30), nullable=True),
    sa.Column('qtd_existente', sa.Integer(), nullable=True),
    sa.Column('qtd_cautelada', sa.Integer(), nullable=True),
    sa.Column('qtd_disp', sa.Integer(), nullable=True),
    sa.Column('qtd_indisp', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('numero_serie', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cl7')
    # ### end Alembic commands ###
