"""numero patrimonio estava duplicado

Revision ID: 5c02ee3f4552
Revises: 1b66dd852f95
Create Date: 2025-09-30 11:40:21.076177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c02ee3f4552'
down_revision = '1b66dd852f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl6', schema=None) as batch_op:
        batch_op.drop_column('numero_patrimonio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl6', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_patrimonio', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
