"""add table CL1 Rações

Revision ID: 626125051c1f
Revises: a816533404d6
Create Date: 2025-10-01 11:30:48.578638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626125051c1f'
down_revision = 'a816533404d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cl1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cl1')
    # ### end Alembic commands ###
