"""init

Revision ID: 6f613f2da1c7
Revises: 
Create Date: 2025-09-25 15:20:02.763011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f613f2da1c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cl2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('situacao', sa.String(length=30), nullable=True),
    sa.Column('qtd_prevista', sa.Integer(), nullable=True),
    sa.Column('qtd_disp', sa.Integer(), nullable=True),
    sa.Column('qtd_indisp', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cl6',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('situacao', sa.String(length=30), nullable=True),
    sa.Column('qtd_prevista', sa.Integer(), nullable=True),
    sa.Column('qtd_disp', sa.Integer(), nullable=True),
    sa.Column('qtd_indisp', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('numero_serie', sa.String(length=120), nullable=True),
    sa.Column('numero_patrimonio', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cl7',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material', sa.String(length=120), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('numero_serie', sa.String(length=120), nullable=True),
    sa.Column('situacao', sa.String(length=30), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('identity', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('user_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('classe', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'classe', name='uq_userclass_user_classe')
    )
    with op.batch_alter_table('user_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_classes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_classes_user_id'))

    op.drop_table('user_classes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('cl7')
    op.drop_table('cl6')
    op.drop_table('cl2')
    # ### end Alembic commands ###
