"""Classe IX adicionada

Revision ID: 719927db10e6
Revises: 9295383f8eed
Create Date: 2025-12-10 10:38:54.775179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719927db10e6'
down_revision = '9295383f8eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cl9',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_modelo', sa.String(length=160), nullable=False),
    sa.Column('numero_eb', sa.String(length=120), nullable=False),
    sa.Column('situacao', sa.String(length=40), nullable=False),
    sa.Column('localizacao', sa.String(length=80), nullable=True),
    sa.Column('destino_missao', sa.String(length=180), nullable=True),
    sa.Column('motivo_indisponibilidade', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_eb')
    )
    op.create_table('cl9_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cl9_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('dados_antes', sa.JSON(), nullable=True),
    sa.Column('dados_depois', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cl9_id'], ['cl9.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cl9_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cl9_logs_cl9_id'), ['cl9_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl9_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cl9_logs_cl9_id'))

    op.drop_table('cl9_logs')
    op.drop_table('cl9')
    # ### end Alembic commands ###
