"""Remover item_id; usar PK auto

Revision ID: 76899bc775ac
Revises: 
Create Date: 2025-09-22 15:04:20.208681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76899bc775ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl2', schema=None) as batch_op:
        batch_op.drop_column('item_id')

    with op.batch_alter_table('cl6', schema=None) as batch_op:
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl6', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('cl2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
