"""classe 6 add material

Revision ID: 9295383f8eed
Revises: 4b298bbd2465
Create Date: 2025-12-01 15:55:00.950365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9295383f8eed'
down_revision = '4b298bbd2465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl6', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl6', schema=None) as batch_op:
        batch_op.drop_column('material')

    # ### end Alembic commands ###
