"""add cl1 cardapios and log

Revision ID: ecef16cd70e3
Revises: 626125051c1f
Create Date: 2025-11-27 15:24:51.492779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecef16cd70e3'
down_revision = '626125051c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cl1_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cl1_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('dados_antes', sa.JSON(), nullable=True),
    sa.Column('dados_depois', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cl1_id'], ['cl1.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cl1_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cl1_logs_cl1_id'), ['cl1_id'], unique=False)

    with op.batch_alter_table('cl1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cardapio1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cardapio2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cardapio3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cardapio4', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('menu_atual', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('lote', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl1', schema=None) as batch_op:
        batch_op.drop_column('lote')
        batch_op.drop_column('menu_atual')
        batch_op.drop_column('cardapio4')
        batch_op.drop_column('cardapio3')
        batch_op.drop_column('cardapio2')
        batch_op.drop_column('cardapio1')

    with op.batch_alter_table('cl1_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cl1_logs_cl1_id'))

    op.drop_table('cl1_logs')
    # ### end Alembic commands ###
