"""atualizacao tabela

Revision ID: ee419b63bcfc
Revises: 4dc051799b11
Create Date: 2025-09-23 14:02:36.014314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee419b63bcfc'
down_revision = '4dc051799b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl7', schema=None) as batch_op:
        batch_op.drop_column('qtd_disp')
        batch_op.drop_column('qtd_indisp')
        batch_op.drop_column('qtd_existente')
        batch_op.drop_column('qtd_cautelada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl7', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_cautelada', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('qtd_existente', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('qtd_indisp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('qtd_disp', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
