"""alteração no classe 6

Revision ID: 1b66dd852f95
Revises: 2145d4dc8c0b
Create Date: 2025-09-30 11:28:23.305490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b66dd852f95'
down_revision = '2145d4dc8c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl6', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situacao_patrimonial', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('codot_item_material', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('numero_patrimonio_material', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('ano_fabricacao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disponibilidade', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('valor_inclusao_carga', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('localizacao_atual', sa.String(length=120), nullable=True))
        batch_op.drop_column('valor')
        batch_op.drop_column('observacao')
        batch_op.drop_column('qtd_disp')
        batch_op.drop_column('situacao')
        batch_op.drop_column('qtd_indisp')
        batch_op.drop_column('nome')
        batch_op.drop_column('qtd_prevista')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl6', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_prevista', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('qtd_indisp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('situacao', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('qtd_disp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('valor', sa.NUMERIC(precision=12, scale=2), nullable=True))
        batch_op.drop_column('localizacao_atual')
        batch_op.drop_column('valor_inclusao_carga')
        batch_op.drop_column('categoria')
        batch_op.drop_column('disponibilidade')
        batch_op.drop_column('ano_fabricacao')
        batch_op.drop_column('numero_patrimonio_material')
        batch_op.drop_column('codot_item_material')
        batch_op.drop_column('situacao_patrimonial')

    # ### end Alembic commands ###
