"""erro banco de dados corrigido?

Revision ID: 9e7532de1f8a
Revises: 5c02ee3f4552
Create Date: 2025-09-30 14:08:48.404348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7532de1f8a'
down_revision = '5c02ee3f4552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl7', schema=None) as batch_op:
        batch_op.alter_column('pelotao',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cl7', schema=None) as batch_op:
        batch_op.alter_column('pelotao',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
